# Generated by Django 5.1.3 on 2024-12-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Base_App", "0002_alter_itemlist_category_name_alter_items_item_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="Image",
            field=models.ImageField(blank=True, upload_to="Items/"),
        ),
    ]
